export const BlogCategories = [
  "Accounts",
  "Bookkeeping",
  "Business",
  "Business Advice",
  "Cash",
  "Collection",
  "Contracts",
  "Ecommerce",
  "Entrepreneur Interviews",
  "Freelancer",
  "Invoices",
];

const BlogData = [
  {
    id: 1,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Ecommerce",
  },
  {
    id: 2,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Accounts",
  },
  {
    id: 3,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Contracts",
  },
  {
    id: 4,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Freelancer",
  },
  {
    id: 5,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Invoices",
  },
  {
    id: 6,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Entrepreneur Interviews",
  },
  {
    id: 7,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Cash",
  },
  {
    id: 8,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Bookkeeping",
  },
  {
    id: 9,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Business",
  },
  {
    id: 10,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Accounts",
  },
  {
    id: 11,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Business",
  },
  {
    id: 12,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Contracts",
  },
  {
    id: 13,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Misc",
  },
  {
    id: 14,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Freelancer",
  },
  {
    id: 15,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Ecommerce",
  },
  {
    id: 16,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Business Advice",
  },
  {
    id: 17,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Entrepreneur Interviews",
  },
  {
    id: 18,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Bookkeeping",
  },
  {
    id: 19,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Business",
  },
  {
    id: 20,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Accounts",
  },
  {
    id: 21,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Invoices",
  },
  {
    id: 22,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Misc",
  },
  {
    id: 23,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Cash",
  },
  {
    id: 24,
    title: "Privacy Policy for Ecommerce Stores",
    desc: "Include a Privacy Policy for your ecommerce store to be compliant with the law (this policy is required by law) and built trust with your customers.",
    link: "",
    Category: "Collection",
  },
];

export default BlogData;
